{#
MRR periodic snapshot fact table — the core SaaS metric table.
Grain: one row per (subscription_id × mrr_month).

Generated by crossing each subscription against every month it was active
(from subscription_start to subscription_end, or current month if still active).
Each row carries the subscription's MRR for that month plus a movement type
classification that powers the MRR waterfall.

MRR movement types:
  new         — first month for this user (no prior subscription history)
  expansion   — user returned or upgraded; MRR higher than previous month
  contraction — user downgraded; MRR lower than previous month
  reactivation— user returned after a gap with same MRR
  retained    — same subscription, same MRR as previous month
  churned     — synthetic end-of-life row at cancellation month
#}

with subscriptions as (

    select *
    from {{ ref('fct_subscriptions') }}
    where subscription_start_date is not null

),

-- Generate every calendar month in the reporting window
date_spine as ( -- noqa: disable=TMP

    {{ dbt_utils.date_spine(
        datepart   = "month",
        start_date = "cast('{{ var(\"reporting_start_date\", \"2022-01-01\") }}' as date)",
        end_date   = "add_months(date_trunc('month', current_date()), 1)"
    ) }}

), -- noqa: enable=TMP

months as (

    select
        date_month as month_start_date,
        date_format(date_month, 'yyyyMM') as mrr_month
    from date_spine

),

-- Expand each subscription to one row per active month
-- A subscription is active from its start month until its end month (inclusive)
subscription_months as (

    select
        s.sk_subscription_id,
        s.subscription_id,
        s.sk_user_id,
        s.user_id,
        s.sk_plan_id,
        s.plan_id,
        m.mrr_month,
        s.mrr,
        s.billing_cycle,
        s.cohort_month,
        s.is_spike_churn
    from subscriptions as s
    inner join months as m
        on
            m.mrr_month >= date_format(s.subscription_start_date, 'yyyyMM')
            and m.mrr_month <= date_format(
                coalesce(s.subscription_end_date, current_date()),
                'yyyyMM'
            )

),

-- Look back one month per user to classify the MRR movement type
with_lag as (

    select
        *,
        lag(mrr) over (
            partition by user_id
            order by mrr_month
        ) as prev_mrr,
        lag(subscription_id) over (
            partition by user_id
            order by mrr_month
        ) as prev_subscription_id,
        lag(mrr_month) over (
            partition by user_id
            order by mrr_month
        ) as prev_mrr_month

    from subscription_months

),

-- Classify movement type; derive contribution delta vs prior month
classified as (

    select
        -- Keys  -- noqa: LT02
        {{ dbt_utils.generate_surrogate_key(['subscription_id', 'mrr_month']) }} as sk_mrr_id, -- noqa: TMP,PRS,LT02,LT05

        subscription_id,
        sk_subscription_id,
        user_id,
        sk_user_id,
        plan_id,
        sk_plan_id,

        -- dates
        mrr_month,
        cohort_month,

        -- attributes
        billing_cycle,
        case
            -- No prior active month for this user → brand new subscriber
            when prev_mrr_month is null
                                                                then 'new'
            -- Gap of more than 1 consecutive month → reactivation after churn
            when mrr_month > date_format(
                    add_months(
                        to_date(concat(prev_mrr_month, '01'), 'yyyyMMdd'),
                        1
                    ),
                    'yyyyMM'
                )                                               then 'reactivation'
            -- Continuous subscription, MRR went up → expansion (upgrade)
            when mrr > prev_mrr                                 then 'expansion'
            -- Continuous subscription, MRR went down → contraction (downgrade)
            when mrr < prev_mrr                                 then 'contraction'
            -- Same MRR, no gap → retained
            else                                                     'retained'
        end                                                     as mrr_movement_type,

        -- flags
        is_spike_churn,

        -- metrics
        mrr,
        prev_mrr,
        -- MRR delta vs prior month (positive for growth, negative for contraction)
        mrr - coalesce(prev_mrr, 0)                             as mrr_delta

    from with_lag

),

-- Synthetic churn row: one record at the month AFTER subscription ends
-- This allows summing churned_mrr in waterfall queries without extra joins
churn_rows as (

    select
        concat(s.subscription_id, '_churn') as sk_mrr_id,

        s.subscription_id,
        s.sk_subscription_id,
        s.user_id,
        s.sk_user_id,
        s.plan_id,
        s.sk_plan_id,

        -- Churn lands in the first month after subscription ended
        date_format(
            add_months(
                coalesce(s.subscription_end_date, s.cancelled_date),
                1
            ),
            'yyyyMM'
        ) as mrr_month,

        s.cohort_month,

        s.billing_cycle,
        'churned' as mrr_movement_type,

        s.is_spike_churn,

        s.mrr,
        s.mrr as prev_mrr,
        -s.mrr as mrr_delta

    from subscriptions as s
    where
        s.is_churned
        and coalesce(s.subscription_end_date, s.cancelled_date) is not null

)

select * -- noqa: AM07
from classified

union all

select *
from churn_rows
